/* Generated by re2c 0.13.5 on Wed Nov 10 18:09:51 2010 */
#line 1 "conf.re.c"
	/*
 *  conf.re.c
 *  click-server
 *
 * Copyright 2010 (C) Alexandre Kalendarev 
 * 
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" 
 * AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE 
 * IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE 
 * ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE 
 * LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
 * DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR 
 * SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER 
 * CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, 
 * OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE 
 * OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE. 
 */

#include "clicker.h"

#define	EOI	0

//typedef unsigned int uint;
typedef unsigned char uchar;

#define	BSIZE	8192

#define	YYCTYPE		uchar
#define	YYCURSOR	cursor
#define	YYLIMIT		s->lim
#define	YYMARKER	s->ptr
#define	YYFILL(n)	{cursor = fill(s, cursor);}

#define	RET(i)	{s->cur = cursor; return i;}

#include "clicker.h"

unsigned char *fill(Scanner *s, uchar *cursor){
	if(!s->eof) {
		unsigned int cnt = s->tok - s->bot;
		if(cnt){
			memcpy(s->bot, s->tok, s->lim - s->tok);
			s->tok = s->bot;
			s->ptr -= cnt;
			cursor -= cnt;
			s->pos -= cnt;
			s->lim -= cnt;
		}
		if((s->top - s->lim) < BSIZE){
			unsigned char *buf = (uchar*) malloc(((s->lim - s->bot) + BSIZE)*sizeof(uchar));
			memcpy(buf, s->tok, s->lim - s->tok);
			s->tok = buf;
			s->ptr = &buf[s->ptr - s->bot];
			cursor = &buf[cursor - s->bot];
			s->pos = &buf[s->pos - s->bot];
			s->lim = &buf[s->lim - s->bot];
			s->top = &s->lim[BSIZE];
			free(s->bot);
			s->bot = buf;
		}
		if((cnt = read(s->fd, (char*) s->lim, BSIZE)) != BSIZE){
			s->eof = &s->lim[cnt]; *(s->eof)++ = '\n';
		}
		s->lim += cnt;
	}
	return cursor;
}

int scan(Scanner *s){
	unsigned char *cursor = s->cur;
	int ret=0;
std:
	s->tok = cursor;
#line 90 "conf.re.c"



#line 81 "conf.c"
{
	YYCTYPE yych;

	if ((YYLIMIT - YYCURSOR) < 10) YYFILL(10);
	yych = *YYCURSOR;
	switch (yych) {
	case '\t':	goto yy21;
	case '\n':	goto yy23;
	case '\v':
	case '\f':	goto yy14;
	case '\r':	goto yy16;
	case ' ':	goto yy19;
	case '#':	goto yy4;
	case '/':	goto yy2;
	case ';':	goto yy17;
	case 'd':	goto yy6;
	case 'e':	goto yy12;
	case 'h':	goto yy9;
	case 'i':	goto yy10;
	case 'l':	goto yy7;
	case 'o':	goto yy11;
	case 'p':	goto yy8;
	case 'u':	goto yy13;
	default:	goto yy25;
	}
yy2:
	++YYCURSOR;
	switch ((yych = *YYCURSOR)) {
	case '*':	goto yy119;
	default:	goto yy3;
	}
yy3:
#line 180 "conf.re.c"
	{
		printf("unexpected character: %c line %d \n", *s->tok, s->line);
		goto std;
	    }
#line 119 "conf.c"
yy4:
	++YYCURSOR;
#line 95 "conf.re.c"
	{ goto unixcomment; }
#line 124 "conf.c"
yy6:
	yych = *(YYMARKER = ++YYCURSOR);
	switch (yych) {
	case 'a':	goto yy113;
	default:	goto yy3;
	}
yy7:
	yych = *(YYMARKER = ++YYCURSOR);
	switch (yych) {
	case 'o':	goto yy99;
	default:	goto yy3;
	}
yy8:
	yych = *(YYMARKER = ++YYCURSOR);
	switch (yych) {
	case 'i':	goto yy88;
	case 'o':	goto yy89;
	default:	goto yy3;
	}
yy9:
	yych = *(YYMARKER = ++YYCURSOR);
	switch (yych) {
	case 't':	goto yy84;
	default:	goto yy3;
	}
yy10:
	yych = *(YYMARKER = ++YYCURSOR);
	switch (yych) {
	case 'n':	goto yy69;
	default:	goto yy3;
	}
yy11:
	yych = *(YYMARKER = ++YYCURSOR);
	switch (yych) {
	case 'u':	goto yy53;
	default:	goto yy3;
	}
yy12:
	yych = *(YYMARKER = ++YYCURSOR);
	switch (yych) {
	case 'r':	goto yy44;
	default:	goto yy3;
	}
yy13:
	yych = *(YYMARKER = ++YYCURSOR);
	switch (yych) {
	case 'r':	goto yy29;
	default:	goto yy3;
	}
yy14:
	++YYCURSOR;
	yych = *YYCURSOR;
	goto yy28;
yy15:
#line 166 "conf.re.c"
	{ RET(8912); goto std; }
#line 181 "conf.c"
yy16:
	yych = *++YYCURSOR;
	switch (yych) {
	case '\n':	goto yy26;
	default:	goto yy28;
	}
yy17:
	++YYCURSOR;
#line 168 "conf.re.c"
	{  goto std; }
#line 192 "conf.c"
yy19:
	++YYCURSOR;
#line 169 "conf.re.c"
	{  goto std; }
#line 197 "conf.c"
yy21:
	++YYCURSOR;
#line 170 "conf.re.c"
	{ goto std;  }
#line 202 "conf.c"
yy23:
	++YYCURSOR;
yy24:
#line 173 "conf.re.c"
	{
		if(cursor == s->eof) RET(EOI);
		s->pos = cursor; s->line++;
		goto std;
	    }
#line 212 "conf.c"
yy25:
	yych = *++YYCURSOR;
	goto yy3;
yy26:
	yych = *++YYCURSOR;
	goto yy24;
yy27:
	++YYCURSOR;
	if (YYLIMIT <= YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
yy28:
	switch (yych) {
	case '\v':
	case '\f':
	case '\r':	goto yy27;
	default:	goto yy15;
	}
yy29:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'l':	goto yy31;
	default:	goto yy30;
	}
yy30:
	YYCURSOR = YYMARKER;
	goto yy3;
yy31:
	yych = *++YYCURSOR;
	switch (yych) {
	case '.':	goto yy32;
	default:	goto yy30;
	}
yy32:
	yych = *++YYCURSOR;
	switch (yych) {
	case '4':	goto yy34;
	case 'p':	goto yy33;
	default:	goto yy30;
	}
yy33:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'r':	goto yy38;
	default:	goto yy30;
	}
yy34:
	yych = *++YYCURSOR;
	switch (yych) {
	case '0':	goto yy35;
	default:	goto yy30;
	}
yy35:
	yych = *++YYCURSOR;
	switch (yych) {
	case '4':	goto yy36;
	default:	goto yy30;
	}
yy36:
	++YYCURSOR;
#line 160 "conf.re.c"
	{
						s->parm = 15;
						goto param;
					}
#line 277 "conf.c"
yy38:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'e':	goto yy39;
	default:	goto yy30;
	}
yy39:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'f':	goto yy40;
	default:	goto yy30;
	}
yy40:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'i':	goto yy41;
	default:	goto yy30;
	}
yy41:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'x':	goto yy42;
	default:	goto yy30;
	}
yy42:
	++YYCURSOR;
#line 156 "conf.re.c"
	{
						s->parm = 14;
						goto param;
					}
#line 309 "conf.c"
yy44:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'r':	goto yy45;
	default:	goto yy30;
	}
yy45:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'o':	goto yy46;
	default:	goto yy30;
	}
yy46:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'r':	goto yy47;
	default:	goto yy30;
	}
yy47:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'f':	goto yy48;
	default:	goto yy30;
	}
yy48:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'i':	goto yy49;
	default:	goto yy30;
	}
yy49:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'l':	goto yy50;
	default:	goto yy30;
	}
yy50:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'e':	goto yy51;
	default:	goto yy30;
	}
yy51:
	++YYCURSOR;
#line 151 "conf.re.c"
	{
						s->parm = 13;
						goto param;
					}
#line 359 "conf.c"
yy53:
	yych = *++YYCURSOR;
	switch (yych) {
	case 't':	goto yy54;
	default:	goto yy30;
	}
yy54:
	yych = *++YYCURSOR;
	switch (yych) {
	case '.':	goto yy55;
	default:	goto yy30;
	}
yy55:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'd':	goto yy58;
	case 'h':	goto yy57;
	case 'p':	goto yy56;
	default:	goto yy30;
	}
yy56:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'o':	goto yy65;
	default:	goto yy30;
	}
yy57:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'o':	goto yy61;
	default:	goto yy30;
	}
yy58:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'b':	goto yy59;
	default:	goto yy30;
	}
yy59:
	++YYCURSOR;
#line 147 "conf.re.c"
	{
						s->parm = 12;
						goto param;
					}
#line 405 "conf.c"
yy61:
	yych = *++YYCURSOR;
	switch (yych) {
	case 's':	goto yy62;
	default:	goto yy30;
	}
yy62:
	yych = *++YYCURSOR;
	switch (yych) {
	case 't':	goto yy63;
	default:	goto yy30;
	}
yy63:
	++YYCURSOR;
#line 143 "conf.re.c"
	{
						s->parm = 11;
						goto ip_param;
					}
#line 425 "conf.c"
yy65:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'r':	goto yy66;
	default:	goto yy30;
	}
yy66:
	yych = *++YYCURSOR;
	switch (yych) {
	case 't':	goto yy67;
	default:	goto yy30;
	}
yy67:
	++YYCURSOR;
#line 139 "conf.re.c"
	{
						s->parm = 10;
						goto dparam;
					}
#line 445 "conf.c"
yy69:
	yych = *++YYCURSOR;
	switch (yych) {
	case '.':	goto yy70;
	default:	goto yy30;
	}
yy70:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'd':	goto yy71;
	case 'h':	goto yy72;
	case 'p':	goto yy73;
	default:	goto yy30;
	}
yy71:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'b':	goto yy82;
	default:	goto yy30;
	}
yy72:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'o':	goto yy78;
	default:	goto yy30;
	}
yy73:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'o':	goto yy74;
	default:	goto yy30;
	}
yy74:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'r':	goto yy75;
	default:	goto yy30;
	}
yy75:
	yych = *++YYCURSOR;
	switch (yych) {
	case 't':	goto yy76;
	default:	goto yy30;
	}
yy76:
	++YYCURSOR;
#line 126 "conf.re.c"
	{
						s->parm = 4;
						goto dparam;
					}
#line 497 "conf.c"
yy78:
	yych = *++YYCURSOR;
	switch (yych) {
	case 's':	goto yy79;
	default:	goto yy30;
	}
yy79:
	yych = *++YYCURSOR;
	switch (yych) {
	case 't':	goto yy80;
	default:	goto yy30;
	}
yy80:
	++YYCURSOR;
#line 130 "conf.re.c"
	{
						s->parm = 8;
						goto ip_param;
					}
#line 517 "conf.c"
yy82:
	++YYCURSOR;
#line 134 "conf.re.c"
	{
						s->parm = 9;
						goto param;
					}
#line 525 "conf.c"
yy84:
	yych = *++YYCURSOR;
	switch (yych) {
	case 't':	goto yy85;
	default:	goto yy30;
	}
yy85:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'p':	goto yy86;
	default:	goto yy30;
	}
yy86:
	++YYCURSOR;
#line 116 "conf.re.c"
	{
						s->parm = 6;
						goto ip_param;
					}
#line 545 "conf.c"
yy88:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'd':	goto yy93;
	default:	goto yy30;
	}
yy89:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'r':	goto yy90;
	default:	goto yy30;
	}
yy90:
	yych = *++YYCURSOR;
	switch (yych) {
	case 't':	goto yy91;
	default:	goto yy30;
	}
yy91:
	++YYCURSOR;
#line 111 "conf.re.c"
	{
						s->parm = 3;
						goto dparam;
					}
#line 571 "conf.c"
yy93:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'f':	goto yy94;
	default:	goto yy30;
	}
yy94:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'i':	goto yy95;
	default:	goto yy30;
	}
yy95:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'l':	goto yy96;
	default:	goto yy30;
	}
yy96:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'e':	goto yy97;
	default:	goto yy30;
	}
yy97:
	++YYCURSOR;
#line 121 "conf.re.c"
	{
						s->parm = 7;
						goto param;
					}
#line 603 "conf.c"
yy99:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'g':	goto yy100;
	default:	goto yy30;
	}
yy100:
	yych = *++YYCURSOR;
	switch (yych) {
	case '_':	goto yy101;
	case 'f':	goto yy102;
	default:	goto yy30;
	}
yy101:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'l':	goto yy107;
	default:	goto yy30;
	}
yy102:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'i':	goto yy103;
	default:	goto yy30;
	}
yy103:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'l':	goto yy104;
	default:	goto yy30;
	}
yy104:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'e':	goto yy105;
	default:	goto yy30;
	}
yy105:
	++YYCURSOR;
#line 102 "conf.re.c"
	{
						s->parm = 2;
						goto param;
					}
#line 648 "conf.c"
yy107:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'e':	goto yy108;
	default:	goto yy30;
	}
yy108:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'v':	goto yy109;
	default:	goto yy30;
	}
yy109:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'e':	goto yy110;
	default:	goto yy30;
	}
yy110:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'l':	goto yy111;
	default:	goto yy30;
	}
yy111:
	++YYCURSOR;
#line 107 "conf.re.c"
	{
						s->parm = 5;
						goto lparam;
					}
#line 680 "conf.c"
yy113:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'e':	goto yy114;
	default:	goto yy30;
	}
yy114:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'm':	goto yy115;
	default:	goto yy30;
	}
yy115:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'o':	goto yy116;
	default:	goto yy30;
	}
yy116:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'n':	goto yy117;
	default:	goto yy30;
	}
yy117:
	++YYCURSOR;
#line 97 "conf.re.c"
	{
						s->parm = 1;
						goto _bool;
					}
#line 712 "conf.c"
yy119:
	++YYCURSOR;
#line 94 "conf.re.c"
	{ goto comment; }
#line 717 "conf.c"
}
#line 184 "conf.re.c"

//s->tok = cursor; s->parm =3; goto param; 
//(PATH)*";"		{ RET(2001); }
//
	


param:
 s->ptok=cursor;

#line 730 "conf.c"
{
	YYCTYPE yych;
	if ((YYLIMIT - YYCURSOR) < 2) YYFILL(2);
	yych = *YYCURSOR;
	switch (yych) {
	case '-':	goto yy123;
	case '.':
	case '/':	goto yy125;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy126;
	case ':':
	case '@':	goto yy129;
	case ';':	goto yy127;
	default:	goto yy130;
	}
yy123:
	yych = *(YYMARKER = ++YYCURSOR);
	switch (yych) {
	case '-':
	case '.':
	case '/':
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy141;
	case ';':	goto yy143;
	default:	goto yy124;
	}
yy124:
#line 199 "conf.re.c"
	{  goto param; }
#line 882 "conf.c"
yy125:
	yych = *(YYMARKER = ++YYCURSOR);
	switch (yych) {
	case '-':	goto yy141;
	case '.':
	case '/':
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy139;
	case ':':
	case '@':	goto yy133;
	case ';':	goto yy144;
	default:	goto yy124;
	}
yy126:
	yych = *(YYMARKER = ++YYCURSOR);
	switch (yych) {
	case '-':	goto yy141;
	case '.':
	case '/':	goto yy139;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy137;
	case ':':
	case '@':	goto yy133;
	case ';':	goto yy136;
	default:	goto yy124;
	}
yy127:
	++YYCURSOR;
yy128:
#line 195 "conf.re.c"
	{ RET(303); }
#line 1036 "conf.c"
yy129:
	yych = *(YYMARKER = ++YYCURSOR);
	switch (yych) {
	case '.':
	case '/':
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case ':':
	case ';':
	case '@':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy134;
	default:	goto yy124;
	}
yy130:
	yych = *++YYCURSOR;
	goto yy124;
yy131:
	++YYCURSOR;
#line 196 "conf.re.c"
	{ RET(301 ); }
#line 1117 "conf.c"
yy133:
	++YYCURSOR;
	if (YYLIMIT <= YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
yy134:
	switch (yych) {
	case '.':
	case '/':
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case ':':
	case '@':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy133;
	case ';':	goto yy131;
	default:	goto yy135;
	}
yy135:
	YYCURSOR = YYMARKER;
	goto yy124;
yy136:
	yych = *++YYCURSOR;
	goto yy128;
yy137:
	++YYCURSOR;
	if (YYLIMIT <= YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
	switch (yych) {
	case '-':	goto yy141;
	case '.':
	case '/':	goto yy139;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy137;
	case ':':
	case '@':	goto yy133;
	case ';':	goto yy136;
	default:	goto yy135;
	}
yy139:
	++YYCURSOR;
	if (YYLIMIT <= YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
	switch (yych) {
	case '-':	goto yy141;
	case '.':
	case '/':
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy139;
	case ':':
	case '@':	goto yy133;
	case ';':	goto yy144;
	default:	goto yy135;
	}
yy141:
	++YYCURSOR;
	if (YYLIMIT <= YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
	switch (yych) {
	case '-':
	case '.':
	case '/':
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy141;
	case ';':	goto yy143;
	default:	goto yy135;
	}
yy143:
	yych = *++YYCURSOR;
	goto yy128;
yy144:
	++YYCURSOR;
	yych = *YYCURSOR;
	goto yy128;
}
#line 201 "conf.re.c"


_bool: 
 s->ptok=cursor;

#line 1440 "conf.c"
{
	YYCTYPE yych;
	if ((YYLIMIT - YYCURSOR) < 3) YYFILL(3);
	yych = *YYCURSOR;
	switch (yych) {
	case '0':	goto yy151;
	case '1':	goto yy149;
	case ';':	goto yy153;
	case 'o':	goto yy147;
	default:	goto yy155;
	}
yy147:
	yych = *(YYMARKER = ++YYCURSOR);
	switch (yych) {
	case 'f':	goto yy156;
	case 'n':	goto yy158;
	default:	goto yy148;
	}
yy148:
#line 213 "conf.re.c"
	{  goto _bool; }
#line 1462 "conf.c"
yy149:
	++YYCURSOR;
#line 208 "conf.re.c"
	{ RET(101); }
#line 1467 "conf.c"
yy151:
	++YYCURSOR;
#line 209 "conf.re.c"
	{ RET(102); }
#line 1472 "conf.c"
yy153:
	++YYCURSOR;
#line 211 "conf.re.c"
	{ goto std; }
#line 1477 "conf.c"
yy155:
	yych = *++YYCURSOR;
	goto yy148;
yy156:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'f':	goto yy160;
	default:	goto yy157;
	}
yy157:
	YYCURSOR = YYMARKER;
	goto yy148;
yy158:
	++YYCURSOR;
#line 206 "conf.re.c"
	{ RET( 101); }
#line 1494 "conf.c"
yy160:
	++YYCURSOR;
#line 207 "conf.re.c"
	{ RET( 102); }
#line 1499 "conf.c"
}
#line 215 "conf.re.c"


lparam: 
 s->ptok=cursor;

#line 1507 "conf.c"
{
	YYCTYPE yych;
	if ((YYLIMIT - YYCURSOR) < 7) YYFILL(7);
	yych = *YYCURSOR;
	switch (yych) {
	case ';':	goto yy171;
	case 'a':	goto yy167;
	case 'c':	goto yy166;
	case 'd':	goto yy170;
	case 'e':	goto yy164;
	case 'n':	goto yy169;
	case 'w':	goto yy168;
	default:	goto yy173;
	}
yy164:
	yych = *(YYMARKER = ++YYCURSOR);
	switch (yych) {
	case 'r':	goto yy205;
	default:	goto yy165;
	}
yy165:
#line 229 "conf.re.c"
	{  goto lparam; }
#line 1531 "conf.c"
yy166:
	yych = *(YYMARKER = ++YYCURSOR);
	switch (yych) {
	case 'o':	goto yy198;
	default:	goto yy165;
	}
yy167:
	yych = *(YYMARKER = ++YYCURSOR);
	switch (yych) {
	case 'l':	goto yy193;
	default:	goto yy165;
	}
yy168:
	yych = *(YYMARKER = ++YYCURSOR);
	switch (yych) {
	case 'a':	goto yy186;
	default:	goto yy165;
	}
yy169:
	yych = *(YYMARKER = ++YYCURSOR);
	switch (yych) {
	case 'o':	goto yy180;
	default:	goto yy165;
	}
yy170:
	yych = *(YYMARKER = ++YYCURSOR);
	switch (yych) {
	case 'e':	goto yy174;
	default:	goto yy165;
	}
yy171:
	++YYCURSOR;
#line 227 "conf.re.c"
	{ goto std; }
#line 1566 "conf.c"
yy173:
	yych = *++YYCURSOR;
	goto yy165;
yy174:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'b':	goto yy176;
	default:	goto yy175;
	}
yy175:
	YYCURSOR = YYMARKER;
	goto yy165;
yy176:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'u':	goto yy177;
	default:	goto yy175;
	}
yy177:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'g':	goto yy178;
	default:	goto yy175;
	}
yy178:
	++YYCURSOR;
#line 225 "conf.re.c"
	{ RET(6); }
#line 1595 "conf.c"
yy180:
	yych = *++YYCURSOR;
	switch (yych) {
	case 't':	goto yy181;
	default:	goto yy175;
	}
yy181:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'i':	goto yy182;
	default:	goto yy175;
	}
yy182:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'c':	goto yy183;
	default:	goto yy175;
	}
yy183:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'e':	goto yy184;
	default:	goto yy175;
	}
yy184:
	++YYCURSOR;
#line 224 "conf.re.c"
	{ RET(5); }
#line 1624 "conf.c"
yy186:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'r':	goto yy187;
	default:	goto yy175;
	}
yy187:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'n':	goto yy188;
	default:	goto yy175;
	}
yy188:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'i':	goto yy189;
	default:	goto yy175;
	}
yy189:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'n':	goto yy190;
	default:	goto yy175;
	}
yy190:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'g':	goto yy191;
	default:	goto yy175;
	}
yy191:
	++YYCURSOR;
#line 223 "conf.re.c"
	{ RET(4); }
#line 1659 "conf.c"
yy193:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'e':	goto yy194;
	default:	goto yy175;
	}
yy194:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'r':	goto yy195;
	default:	goto yy175;
	}
yy195:
	yych = *++YYCURSOR;
	switch (yych) {
	case 't':	goto yy196;
	default:	goto yy175;
	}
yy196:
	++YYCURSOR;
#line 222 "conf.re.c"
	{ RET(3); }
#line 1682 "conf.c"
yy198:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'n':	goto yy199;
	default:	goto yy175;
	}
yy199:
	yych = *++YYCURSOR;
	switch (yych) {
	case 't':	goto yy200;
	default:	goto yy175;
	}
yy200:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'e':	goto yy201;
	default:	goto yy175;
	}
yy201:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'n':	goto yy202;
	default:	goto yy175;
	}
yy202:
	yych = *++YYCURSOR;
	switch (yych) {
	case 't':	goto yy203;
	default:	goto yy175;
	}
yy203:
	++YYCURSOR;
#line 221 "conf.re.c"
	{ RET(2); }
#line 1717 "conf.c"
yy205:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'r':	goto yy206;
	default:	goto yy175;
	}
yy206:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'o':	goto yy207;
	default:	goto yy175;
	}
yy207:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'r':	goto yy208;
	default:	goto yy175;
	}
yy208:
	++YYCURSOR;
#line 220 "conf.re.c"
	{ RET(1); }
#line 1740 "conf.c"
}
#line 231 "conf.re.c"


ip_param:
 s->ptok=cursor;
 ret =  100;

#line 1749 "conf.c"
{
	YYCTYPE yych;
	if ((YYLIMIT - YYCURSOR) < 2) YYFILL(2);
	yych = *YYCURSOR;
	switch (yych) {
	case '.':
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case ':':	goto yy212;
	case ';':	goto yy214;
	default:	goto yy216;
	}
yy212:
	yych = *(YYMARKER = ++YYCURSOR);
	switch (yych) {
	case '.':
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case ':':
	case ';':	goto yy219;
	default:	goto yy213;
	}
yy213:
#line 238 "conf.re.c"
	{  goto ip_param; }
#line 1787 "conf.c"
yy214:
	++YYCURSOR;
yy215:
#line 237 "conf.re.c"
	{ RET(ret); }
#line 1793 "conf.c"
yy216:
	yych = *++YYCURSOR;
	goto yy213;
yy217:
	yych = *++YYCURSOR;
	goto yy215;
yy218:
	++YYCURSOR;
	if (YYLIMIT <= YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
yy219:
	switch (yych) {
	case '.':
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case ':':	goto yy218;
	case ';':	goto yy217;
	default:	goto yy220;
	}
yy220:
	YYCURSOR = YYMARKER;
	goto yy213;
}
#line 239 "conf.re.c"


dparam:
 s->ptok=cursor;
 ret =  200;

#line 1830 "conf.c"
{
	YYCTYPE yych;
	if ((YYLIMIT - YYCURSOR) < 2) YYFILL(2);
	yych = *YYCURSOR;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy223;
	case ';':	goto yy225;
	default:	goto yy227;
	}
yy223:
	yych = *(YYMARKER = ++YYCURSOR);
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy229;
	case ';':	goto yy228;
	default:	goto yy224;
	}
yy224:
#line 246 "conf.re.c"
	{  goto dparam; }
#line 1868 "conf.c"
yy225:
	++YYCURSOR;
yy226:
#line 245 "conf.re.c"
	{ RET(ret); }
#line 1874 "conf.c"
yy227:
	yych = *++YYCURSOR;
	goto yy224;
yy228:
	yych = *++YYCURSOR;
	goto yy226;
yy229:
	++YYCURSOR;
	if (YYLIMIT <= YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy229;
	case ';':	goto yy228;
	default:	goto yy231;
	}
yy231:
	YYCURSOR = YYMARKER;
	goto yy224;
}
#line 247 "conf.re.c"


unixcomment:	

#line 1908 "conf.c"
{
	YYCTYPE yych;
	if ((YYLIMIT - YYCURSOR) < 2) YYFILL(2);
	yych = *YYCURSOR;
	switch (yych) {
	case '\n':	goto yy236;
	case '\r':	goto yy234;
	default:	goto yy238;
	}
yy234:
	++YYCURSOR;
	switch ((yych = *YYCURSOR)) {
	case '\n':	goto yy239;
	default:	goto yy235;
	}
yy235:
#line 252 "conf.re.c"
	{ goto unixcomment; }
#line 1927 "conf.c"
yy236:
	++YYCURSOR;
yy237:
#line 251 "conf.re.c"
	{  s->line++; goto std; }
#line 1933 "conf.c"
yy238:
	yych = *++YYCURSOR;
	goto yy235;
yy239:
	++YYCURSOR;
	yych = *YYCURSOR;
	goto yy237;
}
#line 253 "conf.re.c"


comment:

#line 1947 "conf.c"
{
	YYCTYPE yych;
	if ((YYLIMIT - YYCURSOR) < 2) YYFILL(2);
	yych = *YYCURSOR;
	switch (yych) {
	case '\n':	goto yy244;
	case '*':	goto yy242;
	default:	goto yy246;
	}
yy242:
	++YYCURSOR;
	switch ((yych = *YYCURSOR)) {
	case '/':	goto yy247;
	default:	goto yy243;
	}
yy243:
#line 265 "conf.re.c"
	{ goto comment; }
#line 1966 "conf.c"
yy244:
	++YYCURSOR;
#line 260 "conf.re.c"
	{
		if(cursor == s->eof) RET(EOI);
		s->tok = s->pos = cursor; s->line++;
		goto comment;
	    }
#line 1975 "conf.c"
yy246:
	yych = *++YYCURSOR;
	goto yy243;
yy247:
	++YYCURSOR;
#line 257 "conf.re.c"
	{ goto std; }
#line 1983 "conf.c"
}
#line 266 "conf.re.c"

}



